### ISSUE TITLE
Choses à faire :

### ISSUE THREAD

**Issue by Polluxin** [MathysC/La-Guidonette#63]
- [x] Changer le logo
- [x] Retirer le numéro de version #67 
- [x] Retirer les menus : Administration, Password, Settings #72 
- [x] Ajuster la taille des icones avec le panier 
- [x] Panier : virer le _cart works!_
- [x] Ajouter la page Home et Products
- [x] Modifier le panier c'est moche !! #64 
- [x] #77
- [x] Translation not found #76 
- [x] #68
- [x] Paiement de la commande : vérifier les entrées utilisateurs et feedback #64 
- [x] Traduire tout les éléments en anglais (page de connexion, de compte...) #78 
- [x] #83 
- [x] accès a Torder et tout a modifier/supprimer
